language: bash

services: docker

env:
  global:
    - secure: "uQZhxe+UV19TRarNd7X/egEXUuVMP/awWXYNztCkcetbFkmAU/2DTzI7oZnJQoEjgF8VeZ9LBasqRyiumSe65CXOTFI0qc6zNRxViHRwPfP7+WSVPqY0kcjXu/37G5Hx3284hvJOUz/2PDNwdCH1u2x9NQezIzW0iDLyE234HtH9M3uBtRTISyadstzrIsMpSdSVzXIV6h41zdwm/WtX1Pc713BS/BcKSv9R5ONj1/We07durngFbjK73XaWv5KXWqpguauj45avgSpZ6zRPZxYQuqzuWbIvXhcQU4tScnLRWdfNmsyhy2W4nCocEAOu7yjbm0+3fIUKM3UGFB7KlAwWzH+ppBvqSJoxpmOWsZxm8IO7gAaxj8HAMav+G1EoA/0KsbKeeN0f6VcGOdBSTyCeHmogmugdXlDq57cwIUJXhM+9NZ1xx7JbSpiP3IrAjymYmcKSVO5gEbQscRfcNXYKj1xldn7Y1rdDjBBHXCkSu3bSSCcMj1BIvhAiiYr57MbCKZjPbu00XsjkaC4yVs9Yw+dSI92N48SJ8qE3Is/xLDEM8oMHHGBnwI8T2cdxLXeDXfg2okK+yigtI5UcmwrM1o47nhKa+b/XPS6K/+WBTPDGzyWmq5Mw8gnGMSVuVqBRe9iYZUDyPU8/CGu4RDQ0+xmXCdU7m2VbUFkV2LI="
    - secure: "RczIBXtm+2yVGu+ubp7g9m3UCfmPXVfYAaqAU02wPDXED4bSadZ2bmYLVjvCsXMIoIbHbuCrYjh2MpUXqG0czXwEj3aM5Fxxe243bUWuG2bCC723HK0Pu5QlULE4SnDC9J0Fdq9PqoX8qPEi2On3ieR3XSBJ4Vk4fFAPNzQlyTqbYX5CG3xfgVSevlUxQOoBJ5C/5rQNR+qMdnpEvnR9am3GMlHBmCxuZ1UKhzLbXvQQGbbGsJV/TrmMizeEeQi8QHrGI7zSaqzVORJF5Sg+BF2N3cVcMXIJX1S+Sy4aw7ZHoMV1zGzb2ehpqRwYVPBuado57ZLv0oneGQ5MD5J6Opa4qJrEiS5g4kWURXKuFwB3HUbfD/4DhdtVS+PTntBzdz+kS6XqzQoVDTe3IUAJTpQTV2yVLea3s2ljKMzyt+i/onTGomO1eRtuaR+sc27qBT9uaSHQ33yvLje5kBWagLmI4ogJx84O2S68B3pXgLAK5U8tXbPutYJmfrNl/ANNmifhYov2PIzNRLa7b7hnQZog0jpjyR1Ae7oOCqsXlBeiAWAs0ZXXh4d5QGDZ90QX43/ypO8lcbvOGikLyzGhXzOxbnDdu0WoxGeKsdzcxlbs5DkAD5UuBwI71tGcPmw7jKcn+PrT1PlX+yV3Vb5rnfKbZtPWysIFc7cqIXlccMA="
  matrix:
    - VERSION=latest

before_script:
  - cd src/
  - IMAGE_NAME="chesszebra/$(echo "$TRAVIS_REPO_SLUG" | cut -c 25-):${VERSION}"

script:
  - docker build -t "$IMAGE_NAME" .

after_success:
  - docker login --username $DOCKER_USER --password $DOCKER_PASS
  - docker push $IMAGE_NAME

after_script:
  - docker images

notifications:
  email: false
